use_frameworks!

platform :ios, '13.0'

target 'DropdownSelection_Example' do
  pod 'DropdownSelection', :path => '../'
  pod 'Then', '~> 3.0.0'
  pod 'SnapKit', '~> 5.6.0'
  target 'DropdownSelection_Tests' do
    inherit! :search_paths

    
  end
end
