use_frameworks!

platform :ios, '10.0'

target 'DropdownSelection_Example' do
  pod 'DropdownSelection', :path => '../'

  target 'DropdownSelection_Tests' do
    inherit! :search_paths

    
  end
end
